#!/bin/bash

# get REDIS_HOST/PORT/DB and SCALER_ENDPOINT
(cat /proc/1/environ; echo) | tr '\000' '\n' > /tmp/jinfo.dat
source /tmp/jinfo.dat

IP_ADDRESS=$(echo $(hostname -I) | tr -d ' ')

# start the jobserver
cd /opt/apps/scivm/jobserver
SCALER_ENDPOINT=$SCALER_ENDPOINT REDIS_HOST=$REDIS_HOST REDIS_PORT=$REDIS_PORT REDIS_DB=$REDIS_DB ENDPOINT=tcp://$IP_ADDRESS:10000 GATEWAY=$IP_ADDRESS:4444 python jobserver.py

