#!/bin/bash

# get REDIS_HOST/PORT/DB and SCALER_ENDPOINT
(cat /proc/1/environ; echo) | tr '\000' '\n' > /tmp/jinfo.dat
source /tmp/jinfo.dat

IP_ADDRESS = $(hostname -I)

# start the jobserver
cd /opt/apps/scivm/jobserver
ENDPOINT=tcp://$IP_ADDRESS:10000 GATEWAY=$IP_ADDRESS:4444 python jobserver.py
